name: Publish Python 🐍 distributions 📦 to TestPyPI
on:
  push:
    branches:
      - "master"
jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI and TestPyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.2.2
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Export requirements
        run: poetry version patch
      - name: Add Test pypi
        run:  poetry config repositories.testpypi https://test.pypi.org/legacy/
      - name: Add token config
        run: poetry config pypi-token.testpypi ${{ secrets.DEV_PYPI_TOKEN }}
      - name: Build
        run: poetry build 
      - name: Publish
        run: poetry publish -r testpypi
      - name: Commit vital-python
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions